apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-client-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Release.Name }}-client
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-client
    spec:
      containers:
        - name: client
          image: {{ .Values.clientImage }}
          imagePullPolicy: Never
          ports:
            - containerPort: 80
