apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-config
data:
  POSTGRES_DB: {{ .Values.postgres.dbName }}
  POSTGRES_USER: your-db-username
  POSTGRES_PASSWORD: your-db-password

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: migrations-configmap
data:
  migrations.sql: |
    -- migrations for Users App
    CREATE TABLE IF NOT EXISTS users (
        id SERIAL PRIMARY KEY,
        username VARCHAR(50) NOT NULL,
        email VARCHAR(100) NOT NULL
    );

    -- migrations for Product App
    CREATE TABLE IF NOT EXISTS products (
        id SERIAL PRIMARY KEY,
        name VARCHAR(100) NOT NULL,
        price INT NOT NULL
    );
