---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-logger-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Release.Name }}-logger
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-logger
    spec:
      initContainers:
        - name: wait-for-kafka
          image: busybox
          command: ['sh', '-c', 'until nc -zv kafka.default 9092; do sleep 1; done']
      containers:
        - name: logger
          image: {{ .Values.logger.image }}
          imagePullPolicy: Never
          ports:
            - containerPort: 8080
          envFrom:
            - configMapRef:
                name: {{ .Release.Name }}-logger-config
