---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-logger-service
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 8080
  selector:
    app: {{ .Release.Name }}-logger
