apiVersion: apps/v1
kind: Deployment
metadata:
  name: greet-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: greet-service
  template:
    metadata:
      labels:
        app: greet-service
    spec:
      containers:
      - name: greet-container
        image: service2:latest
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: greet-service
spec:
  selector:
    app: greet-service
  ports:
  - protocol: TCP
    port: 8080

