clientImage: client:0.2

postgresql:
  global:
    postgresql:
      auth:
          postgresPassword: "demo"
          username: "demo"
          password: "demo"
          database: "demo"
  fullnameOverride: "postgres"
  primary:
    persistence:
      mountPath: /var/lib/postgresql/data
      size: 2Gi

services:
  service1:
    serviceName: service1
    appImage: service1:0.2
    migrationsImage: service1-migrations:0.2
  service2:
    serviceName: service2
    appImage: service2:0.2
    migrationsImage: service2-migrations:0.2
